site_name: mborne.github.io
repo_url: https://github.com/mborne/mborne.github.io
repo_name: mborne/mborne.github.io
edit_uri: edit/main/docs/
theme:
  name: material
  language: fr
  logo: assets/logo-qtw.svg
  features:
    - content.action.edit
nav:
  - Accueil: index.md
  - Les outils: outils/index.md
  - Les fiches: fiches/index.md
  - La veille techno: veille/index.md
  - Les dépôts: depots/index.md
  - Mentions légales: mentions-legales/index.md
plugins:
  - search
  - git-revision-date-localized:
      type: date
extra_javascript:
  - assets/js/main.js
# extra_css:
#   - assets/css/style.css
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - tables
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.escapeall:
      hardbreak: true
  - pymdownx.tabbed:
      alternate_style: true
  # checkbox
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
